import {Inter} from 'next/font/google'
import './globals.css'
import HeaderApp from "../components/Organisms/Header/header-app";
import Footer from "../components/Organisms/Footer/footer";
import {DataProvider} from "../app/provider/contextProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <DataProvider>
            <HeaderApp/>
            {children}
            <Footer/>
        </DataProvider>
        </body>
        </html>
    )
}
